{%- from "kibana/map.jinja" import server with context %}
{%- if server.get('enabled', False) %}
server:
  alert:
    ProcstatRunningKibana:
      if: >-
        procstat_running{process_name="kibana"} == 0
      {% raw %}
      labels:
        severity: warning
        service: kibana
      annotations:
        summary: 'Kibana service is down'
        description: 'Kibana service is down on node {{ $labels.host }}'
      {% endraw %}
{%- endif %}

