{%- from "kibana/map.jinja" import server, monitoring with context %}
{%- if server.get('enabled', False) %}
server:
  alert:
    KibanaProcessInfo:
      if: >-
        procstat_running{process_name="kibana"} == 0
      {% raw %}
      labels:
        severity: info
        service: kibana
      annotations:
        summary: 'Kibana service is down'
        description: 'Kibana service is down on node {{ $labels.host }}'
      {% endraw %}
    KibanaProcessWarning:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) >= count(procstat_running{process_name="kibana"}) * {{ monitoring.service_failed_warning_threshold_percent }}
      {% raw %}
      labels:
        severity: warning
        service: kibana
      annotations:
        summary: 'More than {%- endraw %} {{monitoring.service_failed_warning_threshold_percent*100}}%{%- raw %} of Kibana services are down'
        description: 'More than {%- endraw %} {{monitoring.service_failed_warning_threshold_percent*100}}%{%- raw %} of Kibana services are down'
      {% endraw %}
    KibanaProcessCritical:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) >= count(procstat_running{process_name="kibana"}) * {{ monitoring.service_failed_critical_threshold_percent }}
      {% raw %}
      labels:
        severity: critical
        service: kibana
      annotations:
        summary: 'More than {%- endraw %} {{monitoring.service_failed_critical_threshold_percent*100}}%{%- raw %} of Kibana services are down'
        description: 'More than {%- endraw %} {{monitoring.service_failed_critical_threshold_percent*100}}%{%- raw %} of Kibana services are down'
      {% endraw %}
    KibanaProcessDown:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) == count(procstat_running{process_name="kibana"})
      {% raw %}
      labels:
        severity: down
        service: kibana
      annotations:
        summary: 'All Kibana services are down'
        description: 'All Kibana services are down'
      {% endraw %}
{%- endif %}
