{%- from "kibana/map.jinja" import server, monitoring with context %}
{%- if server.get('enabled', False) %}
server:
  alert:
    KibanaProcessDown:
      if: >-
        procstat_running{process_name="kibana"} == 0
      {% raw %}
      labels:
        severity: minor
        service: kibana
      annotations:
        summary: "Kibana process is down"
        description: "The Kibana process on the {{ $labels.host }} node is down."
      {% endraw %}
    KibanaProcessesDownMinor:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) >= count(procstat_running{process_name="kibana"}) * {{ monitoring.service_failed_warning_threshold_percent }} and count(procstat_running{process_name="kibana"} == 0) < count(procstat_running{process_name="kibana"}) * {{ monitoring.service_failed_critical_threshold_percent }}
      {% raw %}
      labels:
        severity: minor
        service: kibana
      annotations:
        summary: "{%- endraw %}{{monitoring.service_failed_warning_threshold_percent*100}}%{%- raw %} of Kibana processes are down"
        description: "{{ $value }} Kibana processes are down (at least {%- endraw %}{{monitoring.service_failed_warning_threshold_percent*100}}%{%- raw %})."
      {% endraw %}
    KibanaProcessesDownMajor:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) >= count(procstat_running{process_name="kibana"}) * {{ monitoring.service_failed_critical_threshold_percent }} and count(procstat_running{process_name="kibana"} == 0) < count(procstat_running{process_name="kibana"})
      {% raw %}
      labels:
        severity: major
        service: kibana
      annotations:
        summary: "{%- endraw %}{{monitoring.service_failed_critical_threshold_percent*100}}%{%- raw %} of Kibana processes are down"
        description: "{{ $value }} Kibana processes are down (at least {%- endraw %}{{monitoring.service_failed_critical_threshold_percent*100}}%{%- raw %})."
      {% endraw %}
    KibanaServiceOutage:
      if: >-
        count(procstat_running{process_name="kibana"} == 0) == count(procstat_running{process_name="kibana"})
      {% raw %}
      labels:
        severity: critical
        service: kibana
      annotations:
        summary: "Kibana service outage"
        description: "All Kibana processes are down."
      {% endraw %}
{%- endif %}
